### ISSUE TITLE
Add support for `hash` YARA module

### ISSUE THREAD

**Issue by austinbyers** [airbnb/binaryalert#30]
The pre-built `yara-python_3.6.3.zip` does not have support for the [`Hash`](http://yara.readthedocs.io/en/latest/modules/hash.html) module. Trying to add YARA rules with the `hash` module result in the following Lambda error when analyzing in production:

```
internal error: 34: Error
Traceback (most recent call last):
File "/var/task/main.py", line 76, in analyze_lambda_handler
with binary_info.BinaryInfo(os.environ['S3_BUCKET_NAME'], s3_key, ANALYZER) as binary:
File "/var/task/binary_info.py", line 57, in __enter__
self.download_path, original_target_path=self.observed_path)
File "/var/task/yara_analyzer.py", line 52, in analyze
return self._rules.match(target_file, externals=self._yara_variables(original_target_path))
yara.Error: internal error: 34
```

**Comment by austinbyers** [comment]
Relevant: https://github.com/VirusTotal/yara/issues/367
